name: Build

on:
  push:
    branches:
      - main

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        # https://docs.timescale.com/about/latest/release-notes/
        timescale-version:
          - "2.12.2"
        # https://github.com/cloudnative-pg/cloudnative-pg/pkgs/container/postgresql
        postgres-version:
          - 15.4-debian
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |-
            TIMESCALEDB_VERSION=${{ matrix.timescale-version }}
            POSTGRES_VERSION=${{ matrix.postgres-version }}
          # https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/postgres/version.go#L30
          tags: |-
            bennycooly/cloudnative-pg-timescaledb:${{ matrix.postgres-version }}-timescaledb-${{ matrix.timescale-version }}
